
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deployment.yml
- backend/service.yml
- frontend/deployment.yml
- frontend/service.yml

images:
- name: 236510206699.dkr.ecr.us-west-1.amazonaws.com/infra-as-code-aws/production/backend
  newName: 236510206699.dkr.ecr.us-west-1.amazonaws.com/infra-as-code-aws/production/backend
  newTag: v1.1

- name: 236510206699.dkr.ecr.us-west-1.amazonaws.com/infra-as-code-aws/production/frontend
  newName: 236510206699.dkr.ecr.us-west-1.amazonaws.com/infra-as-code-aws/production/frontend
  newTag: v1.0
